# 自動生成されるものはチェック対象から除外する
AllCops:
  Exclude:
    - "db/schema.rb"

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# frozen_string_literal: true　というマジックコメントを付けない
Style/FrozenStringLiteralComment:
  Enabled: false  